[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "Daniel Egger <daniel@eggers-club.de>",
]
categories = ["embedded"]
description = "Peripheral access API for nRF51 microcontrollers"
documentation = "https://docs.rs/nrf51"
keywords = [
    "no-std",
    "arm",
    "cortex-m",
    "nordic",
]
license = "0BSD"
name = "nrf51"
repository = "https://github.com/therealprof/nrf51"
version = "0.4.2"

[dependencies]
bare-metal = "0.1.2"
cortex-m = "0.4.3"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.4.0"

[features]
rt = ["cortex-m-rt"]
